# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.2.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/nodejs-chat-websockets-notifications-example
    # dependencies:
    #   override:
    #     - npm install
    steps:
      - checkout

      # Download and cache dependencies
      # - restore_cache:
      #     keys:
      #     - v1-dependencies-{{ checksum "package.json" }}
      #     # fallback to using the latest cache if no exact match is found
      #     - v1-dependencies-
      - run:
          name: install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: start
          command: npm start
          background: true
      # - test:
      #     pre:
      #       - npm start:
      #           background: true
      #       - sleep 5
      #     override:
      #       - npm test
      #       - npm run protractor
      - run:
          name: test
          command: npm test

      - run:
          name: e2e
          command: |
            sudo npm i -g protractor
            webdriver-manager update
            protractor
